[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.89.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://mayank-kraft.netlify.com"
